Detector mateusz tests
kamsza/moral-dilema-detector pull request #40
Opened 2020-11-14 10:58 UTC by mnabywan

-Dodałem w BaseScenarioGenerator2 object property has_pedestrian łączące scenario z pedestrianem, dzięki czemu w scenario Readerze dobrze wczytuje teraz pieszych obecnych w scenariuszu
-Dodałem parę testów

2020-11-14 11:00 UTC, mnabywan commented on src/main/java/DilemmaDetector/ScenarioReader.java
> +        for (Living_entity entity : scenario.getHas_pedestrian()) {
Wczytanie pieszych podpiętych do scenariusza

2020-11-14 11:01 UTC, mnabywan commented on src/main/java/generator/BaseScenarioGenerator2.java
> +        model.getScenario().addHas_pedestrian(person);
Dołączenie pieszego do scenariusza

2020-11-14 12:21 UTC, Roshoy requested changes
Ogólnie sporo do poprawy w testach, unikamy zależności do innych implementacji jak ognia, jeśli gdzieś indziej się coś sypnie, to nie wiemy czy nas test failuje, bo to co testujemy nie działa, czy gdzieś indziej coś nie działa. 
Unikamy ładowania plików, bo długo to trwa i szczerze jest niepotrzebne w większości przypadków, widze kopiuj-wklej w initach. 
Zrób bardziej opisowe nazwy testów tak, żeby było wiadomo co jest sprawdzane

2020-11-14 12:21 UTC, Roshoy commented on src/main/java/generator/BaseScenarioGenerator2.java
> +        model.getScenario().addHas_pedestrian(person);
nie musisz tłumaczyć czegoś co jest łatwe do zrozumienia z kodu ;)

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/ChangeLineApplierTest.java
> +                            " | Acc: " + mainVehicleActor.getRigidBody().getAcceleration());
w unit testach nie ma potrzeby, żeby był output na konsoli, bardziej sprawdzasz stany, czy są równe temu co oczekujesz (najczęściej ostatni)

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/ChangeLineApplierTest.java
> +        this.model = baseScenarioGenerator2.generate();
Chyba, żeby przetestować ChangeLineApplier, czyli coś do zmiany akcji, to potrzebujesz tylko rigid body, weather, numery linii i szerokość linii, nie potrzebujesz odnosić się do ontologii, tworzyć factory, ani nawet scenariusza czy modelu, zmockój te rzeczy, które potrzebujesz, albo poprzez narzędzie do mockowania, albo poprzez po prostu stworzenie obiektów tej klasy.

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/CollisionDetectorTest.java
> +        this.model = baseScenarioGenerator2.generate();
To samo co wcześniej, stwórz ręcznie listę rigidbody, która będzie zawierała jakieś kolizje albo nie i testuj collision detector. Albo jakoś inaczej, ale nie ładuj rzeczy, których nie potrzebujesz

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/RigidBodyMapperTest.java
> +        this.model = baseScenarioGenerator2.generate();
Tutaj będziesz potrzebował faktycznie model, ale trzeba pomyśleć, czy on musi być generowany przez baseScenarioGenerator? Najlepiej usunąć jakąkolwiek losowość z unit testów, one mają być deterministyczne, a z tego co mi wiadomo to generatory są losowe u nas. A nawet jak nie, to powinien być zrobiony mock Modelu, nie potrzebujesz scenariusza aby potestować Mapper.

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/RigidBodyMapperTest.java
> +        length = PhysicsUtils.CmToMeters(RigidBodyMapper.getProperty(mainVehicle, "length"));
nie widzę potrzeby konwersji, a to daje nam zależność od PhysicsUtils, gdyby w tych utilsach coś przestało działać, to tutaj test by failował i nie wiedzielibyśmy dlaczego

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/RigidBodyMapperTest.java
> +        Assert.assertEquals(length, mainVehicleActor.getRigidBody().getLength(), 0.01);
Jak będziemy tak dokładnie testować, to długo to zejdzie, może da się jakoś przetestować, czy ogólnie rigidbody jest dobrze tworzone, a poszczególne elementy porównywać tylko z nazwą w aktorze?

2020-11-14 12:21 UTC, Roshoy commented on src/test/java/DilemmaDetector/Simulator/RigidBodyMapperTest.java
> +        Actor mainVehicleActor = new Actor(model.getVehicle(), RigidBodyMapper.rigidBodyForMainVehicle(model.getVehicle()));
testujesz rigidbody, nie aktora :P

2020-11-14 14:51 UTC, kbieniasz approved these changes

2020-11-14 14:52 UTC, kbieniasz commented
Zgadzam się z komentarzami Adriana, ale tak to to spoko 👍

2020-11-15 10:41 UTC, KipinskiPiotr reviewed
Ogólnie fajnie, tylko te zależności od innych rzeczy w testach trzeba maksymalnie ograniczyć, tak jak Adrian już z resztą ładnie wyjaśnił.

2020-11-15 16:41 UTC, Roshoy approved these changes

2020-11-15 16:42 UTC, merged