Detector mateusz v3
kamsza/moral-dilema-detector pull request #51
Opened 2020-11-28 09:15 UTC by mnabywan

- Zmiana symulacji - jeśli wykryjemy kolizję z pieszym to nie przerywamy symulacji
- Używam teraz model buildera w GUI

2020-11-28 09:22 UTC, mnabywan commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +                if(Utils.isPedestrian(actor) ){
Zrobiłem taką klasę pomocniczą która ma factory

2020-11-28 09:24 UTC, mnabywan commented on src/main/java/gui/logic/OntologyLogic.java
> +        }
Używam MyFactorySingleton

2020-11-28 09:29 UTC, KipinskiPiotr approved these changes

2020-11-28 11:00 UTC, Roshoy requested changes
Nawet nie wiem czy złapałem wszystko co chciałem, ogólnie duży ten PR znowu, jak wprowadzasz taką zmianę jak MyFactorySingleton, to to może samo w sobie być osobnym PR, ale żebyś dociągną wszystko tak jak trzeba.

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +        int collisionWithPedestrians = 0;
Lepsza nazwa, collisionWithPedestrianCount

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +                    if(collisionWithPedestrians == 1) {
tylko przy pierwszym? Nie chcemy zrobić takiego łańcuszka samoprzedłużającego się? :D

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +                for (Actor actor : collided) {
Wyrzuć fora, w collided jest jeden element tylko (wiem, że nie Ty pisałeś, ale jest na zielono to sprawdzam)

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +            }
Cały ten fragment wygląda jakby był czymś co robimy z wynikiem tej metody, a nie coś co jest potrzebne w tej metodzie. Ale mogę ja to zrobić później, bo chyba ja to tak napisałem źle

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/Utils.java
> +public class Utils {
Definitywnie inna nazwa, można coś w stylu `FactoryWrapper` albo `FactoryUtilsWrapper`, ogólnie chcę odzwierciedlić to, że będzie to klasa czasem lepsza od `factory`, np do `isPedestrian`, albo do `getLivingEntitiesFromActor`

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/Utils.java
> +       */
Umiesz zrobić tak komentarz, żeby intellij potem go czytał jako opis metody? Jakby się dało to byłoby fajnie

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/Main.java
> +//        MyFactory factory = new MyFactory(ontology);
usuń komentarz

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/generator/BaseScenarioGenerator2.java
> +
Powtórzenie kodu, wyciągnij do osobnej funkcji i dystans (i może linia) jako parametr

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/gui/logic/OntologyLogic.java
> +//    }
komentarz usunąć

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/gui/logic/OntologyLogic.java
> +            System.err.println("Problem during loading ontology - file not found");
Gdzie podajesz plik? Możesz podać plik?

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/gui/logic/OntologyLogic.java
> +            factory = MyFactorySingleton.getFactory();
nie ma potrzeby przypisywać null

2020-11-28 11:00 UTC, Roshoy commented on src/main/java/gui/logic/OntologyLogic.java
> +        }
Teraz zauważyłem, ale jak robisz MyFactorySingleton, to wszystkie konstruktory MyFactory powinny być prywatne, albo chociaż nie powinno być żadnego użycia MyFactory() po za Singletonem, a widzę już 13 linijek niżej, że jest.

2020-11-28 11:02 UTC, Roshoy commented
Dobra, nie zauważyłem, że to nie Ty dodałeś ten Singleton xD Ale trzeba go rozbudować, żeby pasował do naszego kodu.

2020-11-28 11:07 UTC, mnabywan commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +                    if(collisionWithPedestrians == 1) {
Wcześniej miałem taki łańcuszek, ale uznałem że paru pieszych powinno nas zatrzymać :D

2020-11-28 11:18 UTC, mnabywan commented on src/main/java/gui/logic/OntologyLogic.java
> +            System.err.println("Problem during loading ontology - file not found");
getFactory może rzucić ten wyjątek

2020-11-28 11:21 UTC, kbieniasz commented on src/main/java/DilemmaDetector/Simulator/Utils.java
> +       */
Jak coś to grupa generująca ma javadoci
![image](https://user-images.githubusercontent.com/43828836/100514350-2fa14e80-3174-11eb-9ab3-fbd6449177ab.png)

2020-11-28 11:21 UTC, kbieniasz approved these changes

2020-11-28 11:23 UTC, Roshoy commented on src/main/java/DilemmaDetector/Simulator/SimulatorEngine.java
> +                    if(collisionWithPedestrians == 1) {
Można dodać redukcję prędkości jak jedziemy dalej, a walnęliśmy w coś "miękkiego"

2020-11-29 14:05 UTC, KipinskiPiotr commented on src/main/java/DilemmaDetector/Consequences/CollisionConsequencePredictor.java
> +//    }
Już to usunąłem i zamergowałem, nie ma sensu trzymać tego komentarza.

2020-11-29 16:42 UTC, Roshoy approved these changes

2020-11-29 16:42 UTC, Roshoy commented on src/main/java/DilemmaDetector/Consequences/CollisionConsequencePredictor.java
> +//    }
komentarze, wiesz co zrobić

2020-11-29 20:04 UTC, merged